# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minConflict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('crn', models.IntegerField(unique=True)),
                ('course_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3)),
                ('frequency', models.IntegerField()),
                ('professor', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('num_enrolled', models.IntegerField()),
                ('final_schedule', models.TextField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
