# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minConflict', '0002_auto_20180225_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('major', models.CharField(max_length=100)),
                ('preferred_courses', models.TextField()),
                ('final_courses', models.TextField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
