# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minConflict', '0005_auto_20180225_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_enrolled',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
