# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minConflict', '0013_auto_20180227_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
