# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minConflict', '0019_major'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='major',
            table='majors',
        ),
    ]
