# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minConflict', '0020_auto_20180301_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
